### ISSUE TITLE
Error with follower_dot-plot

### ISSUE THREAD

**Issue by RomainSohier** [Arf9999/rtweetXtras#2] opened 2020-12-03 13:19 UTC
Hi, I just go this error 
follower_dot_plot(rsr_followers, point_colour = "earliest_follow")

Scale for 'colour' is already present. Adding another
scale for 'colour', which will replace the existing
scale.

Error in as.Date.numeric(value) : 'origin' must be supplied 

Here is the traceback 
>>>>
30.
stop("'origin' must be supplied") 
29.
as.Date.numeric(value) 
28.
as.Date(value) 
27.
`[<-.Date`(`*tmp*`, finite & x < range[1], value = NA_real_) 
26.
`[<-`(`*tmp*`, finite & x < range[1], value = NA_real_) 
25.
f(...) 
24.
self$oob(x, range = limits) 
23.
f(...) 
22.
self$rescaler(x, from = range) 
21.
f(..., self = self) 
20.
self$rescale(self$oob(x, range = limits), limits) 
19.
f(..., self = self) 
18.
self$map(df[[j]]) 
17.
FUN(X[[i]], ...) 
16.
lapply(aesthetics, function(j) self$map(df[[j]])) 
15.
f(..., self = self) 
14.
scale$map_df(df = df) 
13.
FUN(X[[i]], ...) 
12.
lapply(scales$scales, function(scale) scale$map_df(df = df)) 
11.
unlist(lapply(scales$scales, function(scale) scale$map_df(df = df)), 
    recursive = FALSE) 
10.
FUN(X[[i]], ...) 
9.
lapply(data, scales_map_df, scales = npscales) 
8.
ggplot_build.ggplot(x) 
7.
ggplot_build(x) 
6.
print.ggplot(plot) 
5.
print(plot) 
4.
print(plot) 
3.
withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) 
2.
suppressWarnings(print(plot)) 
1.
follower_dot_plot(rsr_followers, point_colour = "earliest_follow")

**Comment by Arf9999** [comment] 2020-12-03 15:20
The warning about colour scales is due to some laziness on my part. I have a number of "if" checks for colour scales where some should be "if... else".  This won't effect the plot, it's just a warning because two colour scales have been defined in sequence.  Only the final one is used.

I can't reproduce the 'origin must be supplied' error.  Can you share the data that you're getting it with as a gist?

It is likely happening with a date vector somewhere, but I can't reproduce.

Thanks for the feedback.

**Comment by RomainSohier** [comment] 2020-12-03 16:28
Hi

This one :

afm_followers <- rtweetXtras::get_followers_fast("afm_marketing")

follower_dot_plot(afm_followers, point_colour = "earliest_follow")

Maybe I have to change my r setting or somewhat ...

But I'm not an expert in R, I just auto-learn since 6 months (when I have the time)

All the other codes are ok, you package is very nice !




[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : jeudi 3 décembre 2020 16:20
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Error with follower_dot-plot (#2)


The warning about colour scales is due to some laziness on my part. I have a number of "if" checks for colour scales where some should be "if... else". This won't effect the plot, it's just a warning because two colour scales have been defined in sequence. Only the final one is used.

I can't reproduce the 'origin must be supplied' error. Can you share the data that you're getting it with as a gist?

It is likely happening with a date vector somewhere, but I can't reproduce.

Thanks for the feedback.

**Comment by Arf9999** [comment] 2020-12-04 08:54
Hi,  I still can't reproduce the error. I have changed one small item, and have committed a new version this morning to fix the warnings about colour scales.  Please try download and try again and tell me if you still have the issue.

![image](https://user-images.githubusercontent.com/36820513/101127799-f8fd8500-3606-11eb-9092-c271383db64b.png)

**Comment by RomainSohier** [comment] 2020-12-04 10:06
Hi Andrew,

It seems that I got a bug when i download on Github ...
I already have these problemes on other packages that come from Github (a kind a bug when downloading binary versions of package ..)

I let you know if it works when I'll download ...
Thank you for your help !


[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : vendredi 4 décembre 2020 09:55
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Error with follower_dot-plot (#2)


Hi, I still can't reproduce the error. I have changed one small item, and have committed a new version this morning to fix the warnings about colour scales. Please try download and try again and tell me if you still have the issue.

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F36820513%2F101127799-f8fd8500-3606-11eb-9092-c271383db64b.png&data=04%7C01%7Crsohier%40em-normandie.fr%7C2aeb4bba83bc455df1ed08d898324e03%7Cdffef3d7143e41ed815d9c383c48eb95%7C1%7C0%7C637426689117574917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GEWDX%2FChV25eWzXYvk76Np5LjN1Y7oGLSD9cjqO453A%3D&reserved=0>

**Comment by RomainSohier** [comment] 2020-12-04 13:06
Hi Andrew

I got the same error.

I download the new version and updated all packages.

Do you think that the issue could appear because I leave in France and my date.time is not the same as yours ?



[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : vendredi 4 décembre 2020 09:55
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Error with follower_dot-plot (#2)


Hi, I still can't reproduce the error. I have changed one small item, and have committed a new version this morning to fix the warnings about colour scales. Please try download and try again and tell me if you still have the issue.

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F36820513%2F101127799-f8fd8500-3606-11eb-9092-c271383db64b.png&data=04%7C01%7Crsohier%40em-normandie.fr%7C2aeb4bba83bc455df1ed08d898324e03%7Cdffef3d7143e41ed815d9c383c48eb95%7C1%7C0%7C637426689117574917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GEWDX%2FChV25eWzXYvk76Np5LjN1Y7oGLSD9cjqO453A%3D&reserved=0>

**Comment by Arf9999** [comment] 2020-12-04 20:32
Hi, as I said, I wasn't able to reproduce the issue.  Can you let me know what system you're using? MacOS, Windows, Linux? Also please let me know which version of R & RStudio

I don't have access to a Windows machine to test, but have tested on a Linux machine. Seems ok.

There shouldn't be an issue with dates between countries, we're using rtweet which stores the dates according to the system timezone.

**Comment by RomainSohier** [comment] 2020-12-04 20:55
Hi

I'm on windows

Here are the information - R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)


And [1] ‘1.2.5033’ for Rstudio

Bye !


[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : vendredi 4 décembre 2020 21:32
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Error with follower_dot-plot (#2)


Hi, as I said, I wasn't able to reproduce the issue. Can you let me know what system you're using? MacOS, Windows, Linux? Also please let me know which version of R & RStudio

I don't have access to a Windows machine to test, but have tested on a Linux machine. Seems ok.

There shouldn't be an issue with dates between countries, we're using rtweet which stores the dates according to the system timezone.

**Comment by Arf9999** [comment] 2020-12-04 20:57
I'm going to find someone with windows to test.

**Comment by RomainSohier** [comment] 2020-12-04 20:59
Thanks !

Anyway, all other fonctions are very good 🙂


[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : vendredi 4 décembre 2020 21:57
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Error with follower_dot-plot (#2)


I'm going to find someone with windows to test.

**Comment by Arf9999** [comment] 2020-12-04 21:25
I've made another change to that particular plot function which may fix the issue for you.  If you have some time, please download the latest version (0.2.5.0000) and test.

Thanks for your help in picking up the issues.

**Comment by RomainSohier** [comment] 2020-12-04 22:15
Oh it works !

[cid:ceb5e46a-135a-4c60-b3cf-6dbb02628b6b]
What was the problem ?

[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : vendredi 4 décembre 2020 22:25
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Error with follower_dot-plot (#2)


I've made another change to that particular plot function which may fix the issue for you. If you have some time, please download the latest version (0.2.5.0000) and test.

Thanks for your help in picking up the issues.

**Comment by Arf9999** [comment] 2020-12-05 10:36
Using the `scale_color_viridis_c` function in ggplot with dates converts the labels with dates to numbers, so it is necessary to force them back to dates. 

I was previously using this option to do this:
`labels = lubridate::as_date`
And it seemed to work fine on all 'nix based OS (Linux/MacOS) because lubridate uses the Unix epoch and has an intrinsic origin date of "1970-01-01". It seems that this isn't standard in Windows and I can't figure out how to specify the origin without introducing other errors.

So I searched on stackoverflow :smile:

Instead of using `as_date`, I added a different option to the `scale_colour_viridis_c` function.

 `trans = "date"`

**Closed** 2020-12-05 11:14 UTC

**Comment by RomainSohier** [comment] 2020-12-05 12:59
Ok !!

Anyway, very good package, fast and good data viz !


[EM Normandie]<http://www.ecole-management-normandie.fr/>
Romain SOHIER
Docteur en Sciences de Gestion
Enseignant-chercheur en Marketing
Assistant Professor in Marketing

Tél.: +33 (0)2 32 92 58 40
[Accreditation EM Normandie]<https://www.ecole-management-normandie.fr/ecole/l-em-normandie/accreditations.html>


________________________________
De : Andrew Fraser <notifications@github.com>
Envoyé : samedi 5 décembre 2020 11:36
À : Arf9999/rtweetXtras <rtweetXtras@noreply.github.com>
Cc : SOHIER Romain <rsohier@em-normandie.fr>; Author <author@noreply.github.com>
Objet : Re: [Arf9999/rtweetXtras] Error with follower_dot-plot (#2)


Using the scale_color_viridis_c function in ggplot with dates converts the labels with dates to numbers, so it is necessary to force them back to dates.

I was previously using this option to do this:
labels = lubridate::as_date
And it seemed to work fine on all 'nix based OS (Linux/MacOS) because lubridate uses the Unix epoch and has an intrinsic origin date of "1970-01-01". It seems that this isn't standard in Windows and I can't figure out how to specify the origin without introducing other errors.

So I searched on stackoverflow 😄

Instead of using as_date, I added a different option to the scale_colour_viridis_c function.

trans = "date"
